name: Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Go
        uses: actions/setup-go@v3
        with:
          go-version: "1.23.1"

      - name: Build application
        run: |
          mkdir -p build
          GOOS=linux GOARCH=amd64 go build -ldflags "-X main.version=${{ github.sha }}" -o build/app-${{ github.sha }} cmd/main.go

      - name: Upload binary to server
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          source: "build/app-${{ github.sha }}"
          target: "/home/akirakayoo-server/"

      - name: Post-deployment actions on server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          script: |
            cd /home/akirakayoo-server
            chmod +x app-${{ github.sha }}
            ln -sf /home/akirakayoo-server/app-${{ github.sha }} /home/akirakayoo-server/app-current
            echo "Deployment complete. New binary: app-${{ github.sha }}"
