name: Deploy
permissions:
  contents: write
  issues: write

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Go
        uses: actions/setup-go@v3
        with:
          go-version: "1.23.1"

      - name: Build application as app-current
        run: |
          mkdir -p build
          GOOS=linux GOARCH=amd64 go build -ldflags "-X main.version=${{ github.sha }}" -o build/app-current cmd/main.go

      # - name: Create GitHub Release
      #   id: create_release
      #   uses: softprops/action-gh-release@v1
      #   with:
      #     tag_name: v${{ github.sha }}
      #     name: "Release ${{ github.sha }}"
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # - name: Upload Release Asset
      #   uses: softprops/action-gh-release@v1
      #   with:
      #     files: build/app-current
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload binary to server
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          source: "build/app-current"
          target: "/home/akirakayoo-server/"

      - name: Set permissions and restart service
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          script: |
            chmod +x /home/akirakayoo-server/app-current
            sudo systemctl restart akirakayoo-server.service
